language: node_js
node_js:
  - "4.1"
python: "3.9"
sudo: required
services:
  - docker
before_install:
  - chmod +x ./scripts/*.sh
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  - export PATH=~/bin:$PATH
before_script:
  - aws ecr get-login --no-include-email --region eu-west-1 | sh
script:
  - make all-the-dockers
  - make docker-tag
  - make docker-push
after_success: travis_wait ./scripts/deploy.sh
