---
dist: focal
language: node_js
node_js:
  - "4.1"
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - awscli
before_install:
  - chmod +x ./scripts/*.sh
  - aws --version
before_script:
  - aws ecr get-login --no-include-email --region eu-west-1 | sh
script:
  - make all-the-dockers
  - make docker-tag
  - make docker-push
after_success: travis_wait ./scripts/deploy.sh
