language: node_js
node_js:
  - "4.1"
sudo: required
services:
  - docker
before_install:
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  - export PATH=~/bin:$PATH
before_script:
  - aws ecr get-login --no-include-email --region eu-west-1 > docker_login.sh
  - chmod +x docker_login.sh
  - ./docker_login.sh
after_success:
  - make all-the-dockers
  - make docker-tag
  - make docker-push